name: CI & Release

on:
  workflow_dispatch:
  push:
    branches:
        - main
    tags:  
        - 'v*'

permissions:
  contents: write

jobs:
  ci:
    name: "C.I"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: sudo apt install libatk1.0-dev pkg-config libgtk-3-dev

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install cross
        run: cargo install cross

      - name: Build ubuntu version
        run: cargo build --release --locked

      - name: Build Windows version (with cross)
        run: cross build --target x86_64-pc-windows-gnu --release --locked
      
      - name: Prepare artifact (if release)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mv  target/release/easy_flash_daplink easy_flash_daplink
          mv  target/x86_64-pc-windows-gnu/release/easy_flash_daplink.exe easy_flash_daplink.exe

      - name: Create artifact (if release)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: build_output
          path: |
            easy_flash_daplink
            easy_flash_daplink.exe

  
  # only generate release if push on tags
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build_output

      - name: Create Windows archive /w XPack OpenOCD
        run: |
          curl -LO https://github.com/xpack-dev-tools/openocd-xpack/releases/download/v0.12.0-4/xpack-openocd-0.12.0-4-win32-x64.zip
          unzip xpack-openocd-0.12.0-4-win32-x64.zip
          mkdir windows
          mv easy_flash_daplink.exe windows/
          mv xpack-openocd-0.12.0-4/bin/* windows/
          mv xpack-openocd-0.12.0-4/openocd/scripts/ windows/
          7z a windows.zip windows/*
          rm -rf xpack-openocd-0.12.0-4/ xpack-openocd-0.12.0-4-win32-x64.zip

      - name: Create Linux archive /w XPack OpenOCD
        run: |
          curl -LO https://github.com/xpack-dev-tools/openocd-xpack/releases/download/v0.12.0-4/xpack-openocd-0.12.0-4-linux-x64.tar.gz
          tar xzf xpack-openocd-0.12.0-4-linux-x64.tar.gz
          mkdir linux
          mv easy_flash_daplink linux/
          mv xpack-openocd-0.12.0-4/bin/* linux/
          mv xpack-openocd-0.12.0-4/openocd/scripts/ linux/
          7z a linux.zip linux/*
          rm -rf xpack-openocd-0.12.0-4/ xpack-openocd-0.12.0-4-linux-x64.tar.gz

      - name: Renanme release file
        run: |
          mv windows.zip easy_flash_daplink-${{github.ref_name}}-windows.zip
          mv linux.zip easy_flash_daplink-${{github.ref_name}}-linux.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          make_latest: true
          files: |
              easy_flash_daplink-${{github.ref_name}}-windows.zip
              easy_flash_daplink-${{github.ref_name}}-linux.zip